### ISSUE TITLE
[Feature Request] 菜单可以展示总页数

### ISSUE THREAD

**Issue by anig1scur** [YanhuiJessica/Chickeat#1]
RT， 现在的 checkeat 只能知道所在页以及 <下一页> <上一页>， 并不能总览页数

![image](https://user-images.githubusercontent.com/52899668/144739774-58d455a9-cf71-450b-a39d-f76fa83839ea.png)

**Comment by YanhuiJessica** [comment]
迅速加上了！XD

**Comment by anig1scur** [comment]
> 迅速加上了！XD

靠 专门等我提一个 PR 是吧!

**Comment by YanhuiJessica** [comment]
> 靠 专门等我提一个 PR 是吧!

本来我说的是下次，但看在你这么积极的份上 🤪

![image](https://user-images.githubusercontent.com/52900008/144740089-0d824ef9-1f5c-4b46-9179-36a6f75ce389.png)
