### ISSUE TITLE
[Feature Request] 关键食材触发菜谱

### ISSUE THREAD

**Issue by anig1scur** [YanhuiJessica/Chickeat#2]
比如我想吃蘑菇

/food @chickeat  蘑菇

就可以给我列出现有的包括蘑菇食材的菜品：

1. 香菇炒肉
2.  小鸡炖蘑菇

**Comment by YanhuiJessica** [comment]
不得不说，这个真的可以有！

**Comment by YanhuiJessica** [comment]
借助于 OpenAI Text Completion 可以完成以上需求（如有其它建议可以再次 Open
