### ISSUE TITLE
[Feature Request] 分种类分时段推荐

### ISSUE THREAD

**Issue by anig1scur** [YanhuiJessica/Chickeat#3]
现在似乎是时间段内 random 所有菜 ，但是很多东西并不适合在早上吃，比如麻辣烫。并且一餐可以分种类：
1. 正餐
2. 水果
3. 饮品

综合推荐

**Comment by YanhuiJessica** [comment]
现在是支持为菜品添加类别标签的，后续会把推荐的「类别」、「数量」设置考虑到每日推荐里

**Comment by YanhuiJessica** [comment]
现在每日推荐数量和种类设置的基本功能已经有啦 XD
